### ISSUE TITLE
i got error when use vue-auth

### ISSUE THREAD

**Issue by hainuo** [iWader/vue-auth#1]
![image](https://cloud.githubusercontent.com/assets/421861/18617472/56d14930-7e02-11e6-96bc-d3aec84de4be.png)

how can i do with this.

.babelrc
```
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```
package.json
```
  "dependencies": {
    "babel-runtime": "^6.0.0",
    "vue": "^1.0.21",
    "vue-auth": "^0.4.0",
    "vue-resource": "^1.0.2",
    "vue-router": "^0.7.13",
    "vue-strap": "^1.1.15",
    "vuex": "^1.0.0-rc.2"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-register": "^6.0.0",
    "chai": "^3.5.0",
    "chromedriver": "^2.24.1",
    "connect-history-api-fallback": "^1.1.0",
    "cross-spawn": "^2.1.5",
    "css-loader": "^0.23.0",
    "eslint": "^2.10.2",
    "eslint-config-airbnb-base": "^3.0.1",
    "eslint-friendly-formatter": "^2.0.5",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-html": "^1.3.0",
    "eslint-plugin-import": "^1.8.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.4",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.8.1",
    "http-proxy-middleware": "^0.12.0",
    "inject-loader": "^2.0.1",
    "isparta-loader": "^2.0.0",
    "json-loader": "^0.5.4",
    "karma": "^0.13.15",
    "karma-coverage": "^0.5.5",
    "karma-mocha": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sinon-chai": "^1.2.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.24",
    "karma-webpack": "^1.7.0",
    "lolex": "^1.4.0",
    "mocha": "^2.4.5",
    "nightwatch": "^0.8.18",
    "ora": "^0.2.0",
    "phantomjs-prebuilt": "^2.1.3",
    "selenium-server": "2.53.0",
    "shelljs": "^0.6.0",
    "sinon": "^1.17.3",
    "sinon-chai": "^2.8.0",
    "url-loader": "^0.5.7",
    "vue-hot-reload-api": "^1.2.0",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^8.3.0",
    "vue-style-loader": "^1.0.0",
    "webpack": "^1.12.2",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-hot-middleware": "^2.6.0",
    "webpack-merge": "^0.8.3"
  }
```

**Comment by iWader** [comment]
Its still very alpha at the minute, but it is functional. It looks like you're environment isn't running es6, which at the minute it needs to be as I've not been compiling a dist version just yet.

Your `.babelrc` looks fine to me, so I'm not sure as to why you're getting this error, other than your environment isn't es6. 

I'll get a dist version setup next time I get to work on this.

**Comment by hainuo** [comment]
thanks

**Comment by iWader** [comment]
I've put a dist version online if you're able to install from git for the time being. 

Hopefully I'll have time to test it working tonight and tag a version

**Comment by hainuo** [comment]
I tried it however I got error cannot find protperty beforeEach.  i'm out.Later I'll put screenshot of the error 
------------------ 原始邮件 ------------------
发件人: "Wade Urry"<notifications@github.com>
发送时间: 2016年9月19日(星期一) 下午3:49
收件人: "iWader/vue-auth"<vue-auth@noreply.github.com>;
抄送: "hainuo"<admin@hainuo.info>;"Author"<author@noreply.github.com>;
主题: Re: [iWader/vue-auth] i got error when use vue-auth (#1)



I've put a dist version online if you're able to install from git for the time being. 
 
Hopefully I'll have time to test it working tonight and tag a version
 
&mdash;

**Comment by hainuo** [comment]
```shell
ERROR in ./~/vue-auth/dist/vue-auth.js
Module parse failed: /Users/fengliu/wease/node_modules/vue-auth/dist/vue-auth.js Assigning to rvalue (9:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Assigning to rvalue (9:5)
```

i reinstall use `npm install git+https://github.com/iWader/vue-auth.git` .
![image](https://cloud.githubusercontent.com/assets/421861/18638067/46dd1ce2-7ec1-11e6-97e6-44724ffd47e3.png)

**Comment by hainuo** [comment]
https://github.com/iWader/vue-auth/blob/master/dist/vue-auth.js#L9
I change `global.vue-auth` to `global.VueAuth`.  fixed the bug

**Comment by iWader** [comment]
Hi @hainuo. I've just tagged v4.0.1 which addresses the issue. Theres now a fully working dist version which is linked as the main script in the `package.json`

Thanks for debugging this 👍

**Comment by hainuo** [comment]
tanks
