### ISSUE TITLE
Vue 2 support?

### ISSUE THREAD

**Issue by Samuell1** [iWader/vue-auth#3]

**Comment by iWader** [comment]
This should work with Vue 2 already, the plugin itself doesn't actually do anything specific with Vue, other than registering itself as a plugin.

Currently updating one of my apps and not come across any issues just yet.

**Comment by Samuell1** [comment]
I find this, its deprecated
https://github.com/iWader/vue-auth/blob/master/src/index.js#L85

in new router needs to be "go" changed to "push"

**Comment by iWader** [comment]
Ah, thanks for pointing out 👍 

I've tagged v2.0.0-alpha.1 as a version for Vue 2. You should be able to grab it by installing with `npm install vue-auth@next` for now

**Comment by Samuell1** [comment]
👍 thanks

**Comment by Samuell1** [comment]
@iWader if i try check if user is authenticated (`this.$auth.isAuthenticated()`) i get error from JWT

`Uncaught TypeError: Cannot read property 'split' of null`

I think there be good some inline if to fix it

```
isAuthenticated() {
   return this.hasToken() ? !JWT.isExpired(this.getToken()) : false;
}
```
